name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction

    - name: Run Psalm
      run: ./vendor/bin/psalm
